import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'app_name': 'Sport Live',
          'vpn_detected': 'VPN Detected',
          'security_alert': 'Security Alert',
          'rooted_device_msg':
              'Your device is rooted, please use a non-rooted device to continue using the app',
          'vpn_detected_message':
              'Please turn off your VPN to continue using the app',
          'terms_and_conditions': "terms and Conditions",
          'refund_policy': 'Refund Policy',
          'terms_of_service': 'Terms of Service',
          'privacy_policy': 'Privacy Policy',
          'delete_account': 'Delete Account',
          'delete_account_message': 'Are you sure you want to delete your account?',
          'account_deleted': 'Account Deleted',
          'loading': 'Loading',
          'contact_twitter': 'Contact us on Twitter',
          'error': 'Error',
          'something_went_wrong': 'Something went wrong',
          'retry': 'Retry',
          'not_available': 'Not Available',
          'connect_error': 'Connection Error',
          'connection_error': 'Connection Error',
          'connect_error_message': 'Please check your internet connection',
          'server_error': 'Server Error',
          'server_error_message':
              'Something went wrong, please try again later',
          'no_data': 'No Data',
          'no_data_message': 'No data found',
          'apply': 'Apply',
          'add_to_cart': 'Add to cart',
          'email': 'Email',
          'send': 'Send',
          'logout': 'Logout',
          'exit_confirm_msg': 'Are you sure you want to exit?',
          'vat': 'VAT',
          'yes': 'Yes',
          'no': 'No',
          'now': 'Now',
          'year': 'Year',
          'month': 'Month',
          'day': 'Day',
          'hour': 'Hour',
          'minute': 'Minute',
          "second": "Second",
          "cancel": "Cancel",
          "success": "Success",
          'our_policy': 'Our Policy',
          'policy_desc':
              'We offer a wide range of gift cards that suit all tastes and occasions. We also offer the possibility of creating a custom gift card with your own design and text.',
          'search': 'Search',
          'ready_card_for_you': 'Ready Card For You',
          'done': 'Done',
          // currency
          'balance': 'Balance',
          'sar': 'SAR',
          'sar.': 'SAR',
          //Login
          'login': 'Login',
          'signup': 'Signup',
          'login_to_continue': 'Login to continue',
          'forget_password': 'Forget Password?',
          'restore_password': 'Restore Password',
          'password_reset': 'Password Reset',
          'password_reset_success': 'Password reset successfully',
          'password_required': 'Password is required',
          'not_login_msg': 'You are not logged in',
          'don\'t_have_account': 'Don\'t have an account?',
          'create_account': 'Create an account',
          'first_name': 'First Name',
          'last_name': 'Last Name',
          'password': 'Password',
          'fill_all_fields': 'Please fill all fields',
          // reset password
          'email_sent': 'Reset code sent to email',
          'email_not_sent': 'Email not sent',
          // Profile
          "profile": "Profile",
          "my_account": "My Account",
          "wallet": "Wallet",
          'my_wallet': 'My Wallet',
          'previous_transactions': 'Trans History',
          'transfer_no': 'Transfer No.',
          'operations': 'Operations',
          "current_balance": "Current Balance",
          'add_balance': 'Add Balance',
          'balance_added': 'Balance added',
          'balance_add_failed': 'Balance add failed',
          'transfer_balance': 'Transfer Balance',
          'transfer': 'Transfer',
          'balance_transfered': 'Balance transfered',
          'balance_transfer_failed': 'Balance transfer failed',
          'my_cards': 'My Cards',
          'my_info': 'My Infomations',
          'account_settings': 'Account Settings',
          'support': 'Support',
          'contact_us': 'Contact Us',
          'orders': 'Orders',
          'order_data': 'Order Data',
          'customer_and_recipient': 'Customer & Recipient',
          'id_and_date': 'ID & Date',
          'update_profile': 'Update Profile',
          'update': 'Update',
          'change_password': 'Change Password',
          'old_password': 'Old Password',
          'password_updated': 'Passwoword changed successfully',
          'profile_updated': 'Profile updated',
          'update_failed': 'Update failed',
          'new_password': 'New Password',
          'confirm_password': 'Confirm Password',
          'unmatch_password': 'Password do not match',
          'empty_old_pass': 'Please enter old password',
          'empty_new_pass': 'Please enter your new password',
          'empty_confirm_pass': 'Please confirm your password',
          'password_not_match': 'Passwords do not match',
          // Reminder
          'phone_verify_reminder':
              'Please take a moment and verify your phone number.',
          "verify_phone_description":
              'You will receive the verification code via WhatsApp. Please enter the code below to continue',
          'verify_email_description':
              'You will receive the verification code via email. Please enter the code below to continue',
          // Transfer Balance
          'receiver_email': 'Receiver Email',
          'receiver_phone_number': 'Receiver Phone Number',
          'transfer_success': 'Transfer Success',
          'transfer_failed': 'Transfer Failed',
          // Orders
          "no_orders": "No Orders",
          'order_number': 'Order Number',
          'tax_number': 'Tax Number',
          'card_id': 'Card ID',
          // Cart
          'cart': 'Cart',
          'view_cart': 'View Cart',
          "empty_cart": "'No items in the cart'",
          "delivered": "Delivered",
          "not_delivered": "Not Delivered",
          'delete': 'Delete',
          'add_to_cart_success': 'Added to cart successfully',
          'add_to_cart_failed': 'Failed to add to cart',
          'remove_card': 'Remove Card',
          'remove_card_message': 'Are you sure you want to remove this card?',
          'removing_card': 'Removing Card',
          // Card Preview
          'card_preview': 'Card Preview',
          'customer': 'Customer',
          'view_card': 'View Card',
          'view_invoice': 'View Invoice',
          'date': 'Date',
          'time': 'Time',
          'delivery_not_set': 'Delivery not set',
          'card_ready': 'card is ready to be use',
          'card_used': 'card is used',
          'how_to_use': 'How to use',
          'close': 'Close',
          'description': "Description",
          "card_details": "Card Details",
          "card_info": 'Card Informations',
          'available_until': "Valid Until",
          "card_valid": "Card Validity",
          'follow_instructions': 'Follow the following steps',
          'instruction_1': 'Go to the Store website through Link',
          'instruction_2': 'Copy the promo Code',
          'instruction_3': 'Paste the code in the designated input field',
          'instruction_4': 'Get your discount From Store',
          // HOW to use card
          'step_1': 'Go to the Store website through Link',
          'here': 'here',
          'step_2': 'Copy the promo Code',
          'step_3': 'Paste the code in the designated input field',
          'step_4': 'Get your discount From Store',
          // Home
          'home_body': 'A Gift to Suit Their Taste',
          'home_desc': 'When Gifting Becomes Personal',
          'custom_a_gift': 'Custom a Gift',
          'store_features': 'Store Features',
          "choose_what_suits_you": "Choose What Suits You",
          "gift_cards": "Gift Cards",
          "gift_cards_desc": "Choose a gift card from our wide collection",
          "custom_cards": "Custom Cards",
          "custom_card": "Custom Card",
          "custom_cards_desc": "Create a custom gift card for your loved ones",
          'feature_1': 'Instant Delivery',
          'feature_1_msg':
              'Enjoy instant delivery of the digital card in the email',
          'feature_2': 'Variety',
          'feature_2_msg': 'Choose from a wide range of gift cards',
          'feature_3': 'Safe shopping experience',
          'feature_3_msg': 'Enjoy a safe and secure shopping experience',
          // Payment
          'select_payment_method': 'Select Payment Method',
          'payment_method': 'Payment Method',
          'amount': 'Amount',
          'payment': 'Payment',
          'pay': 'Pay',
          "pay_now": "Pay Now",
          'charge': 'Charge',
          'select_Payment': 'Select Payment',
          'payment_success': 'Payment Success',
          'payment_failed': 'Payment Failed',
          'unselected_payment_msg': 'Please select a payment method',
          'enter_amount_msg': 'Please enter the amount',
          'total_price': 'Total Price',
          'coupon_code': 'Coupon Code',
          'coupon_apply_succ': 'Coupon applied successfully',
          'summary': 'Summary',
          'buy': 'Buy',
          'buy_now': 'Buy Now',
          'payment_success_message': 'Payment success',
          'payment_failed_message': 'Payment failed',
          'paying': 'Paying',
          // Cards
          'card': 'Card',
          'from_behind': 'From behind',
          'custom_a_card': 'Custom A Card',
          'pro_item': 'Pro Item',
          'ready_cards': 'Ready Cards',
          'ready_card': 'Ready Card',
          'cards_title_msg': 'Cards ready for you',
          'creat_a_card': 'Creat A Card',
          'card_price': 'Card Price',
          'empty_message': 'Empty Message',
          'empty_price': 'Price is empty',
          'min_price': 'Minimum Price',
          'send_at': 'Send at',
          "receive_at": "Receive at",
          "choose_time": "Choose Time",
          'celebration_shape': 'Celebration Shape',
          "choose_celebration_shape": "Choose Celebration Shape",
          'celebration_link': 'Celebration Link',
          'choose_celebration_link': 'Choose Celebration Link',
          'pro_color_info':
              'You have selected a premium color. An additional fee will be automatically added to the card price',
          'pro_shape_info':
              'You have selected a premium shape. An additional fee will be automatically added to the card price',
          "celebration_shape_info":
              "You have selected a premium celebrate Shape. An additional fee will be automatically added to the card price",
          "celebration_link_info":
              "You have selected a premium celebrate Link. An additional fee will be automatically added to the card price",
          "card_added_successfully": "Card added successfully",
          'shape_price': 'Shape price',
          'color_price': 'Color Price',
          'celebration_shape_price': 'Celebration Shape Price',
          'celebration_link_price': 'Celebration Link Price',
          // Explore
          'explore': 'Explore',
          'categories': 'Categories',
          'category': 'Category',
          'show_all': 'Show All',
          'partners_offers': 'Partners Offers',
          'popular_shops': 'Popular Shops',
          'latest_cards': 'Latest Cards',
          'offers': 'Offers',
          'no_ads_found': 'No ads found',
          // ready
          'cards': 'Cards',
          'filter': 'Filter',
          'price': 'Price',
          'shop': 'Shop',
          'shops': 'Shops',
          "reciver_info": "Receiver Info",
          "name": "Name",
          // custom
          'color': 'Color',
          'font_type': 'Font Type',
          'font_size': 'Font Size',
          'shape': 'Shape',
          'message': 'Message',
          'receiver_name': 'Receiver name',
          'receiver_whats': 'Receiver\'s Whatsapp',
          'sending_date': 'Sending date',
          'please_enter_name': 'Please enter name',
          'please_enter_phone': 'Please enter phone',
          'phone_sould_not_start_with_0': 'Shouldn\'t start with 0',
          'phone_should_be_9_digits': 'Should be 9 digits',
          'phone_number': 'Phone number',
          'later': 'Later',
          'save': 'Save',
          'next': 'Next',
          'previous': 'Previous',
          // Shops
          'shops_title_msg': 'Stores List',
          'store_name': 'Store Name',
          'store_description': 'Store Decription',
          'store_link': 'Store Link',
          'store': 'Store',
          'no_store': 'No Store',
          // Settings
          'home': 'Home',
          'menu': 'Menu',
          'settings': 'Settings',
          'about_app': 'عن التطبيق',
          'about_app_message':
              'Discover a world of digital gifts! Send personalized e-gift cards to friends and family with just a few taps. Choose from top brands and retailers, perfect for any occasion.',
          'ok': 'Ok',
          // webview
          'open_in_browser': 'Open in browser',
          'copy_link': 'Copy link',
          'copied': 'Copied',
          'leave': 'Leave',
          // Settings
          'verify_phone_msg': 'Please take a moment and verify your phone number',
          'profile_settings': 'Profile Settings',
          'send_code': 'Send Code',
          'sending_code': 'Sending Code',
          'empty_feild': 'Empty Feild',
          'pin_minimim': 'Pin Minimum',
          'verification_sent': "Verification code sent to your whatsapp",
          'phone_verify_success': 'Phone number verified successfully',
          'verify': 'Verify',
          'dark_mode': 'Dark Mode',
          'language': 'Language',
          'notifications': 'Notifications',
          'privacy': 'Privacy',
          'feed_back': 'Feedback',
          'feed_back_message':
              'To help improving our application you can email us',
          'email_clipbord_message': 'Email has been copied',
          'version': 'Version',
          'join_us_msg': 'Join GIVE A GIFT partners',
          // Join Us
          'please_enter_store_name': 'Please enter store name',
          'store_name_must_be_at_least_3_characters':
              'Store name must be at least 3 characters',
          'please_enter_message': 'Please enter message',
          'message_must_be_at_least_10_characters':
              'Message must be at least 10 characters',
          'please_enter_store_description': 'Please enter store description',
          'store_description_must_be_at_least_10_characters':
              'Store decription must be at least 10 characters',
          'please_enter_store_link': 'Please enter store link',
          'please_enter_valid_link': 'Please enter valid link',
          'phone_must_be_at_least_9_digits': 'Phone must be at least 9 digits',
          'please_enter_email': 'Please enter email',
          'please_enter_valid_email': 'Please enter valid email',
          // Contact Us
          'name_must_be_at_least_3_characters':
              'Name must be at least 3 characters',
          'please_enter_description': 'Please enter description',
          'description_must_be_at_least_10_characters':
              'Description must be at least 10 characters',
          // Months
          'month_1': 'January',
          'month_2': 'February',
          'month_3': 'March',
          'month_4': 'April',
          'month_5': 'May',
          'month_6': 'June',
          'month_7': 'July',
          'month_8': 'August',
          'month_9': 'September',
          'month_10': 'October',
          'month_11': 'November',
          'month_12': 'December',
          // support
          'support_1':
              'If you need assistance, feel free to contact our support team',
          'support_2': 'you can visit our Instagram page',
          'support_3': "for more information. We're happy to help",
          // Timing
          'pm': 'PM',
          'am': 'AM',
        },
        'ar': {
          'app_name': 'رياضة مباشرة',
          'security_alert': 'تحذير أمني',
          'rooted_device_msg':
              'جهازك يحتوي صلاحية الروت، يرجى إستخدام جهاز غير مروت لمواصلة إستخدام التطبيق',
          'vpn_detected': 'تم الكشف عن VPN',
          'vpn_detected_message': 'يرجى إيقاف VPN لمواصلة استخدام التطبيق',
          'contact_twitter': 'تواصل معنا على تويتر',
          'error': 'خطأ',
          'something_went_wrong': 'حدث خطأ ما',
          'terms_and_conditions': "الشروط والأحكام",
          'refund_policy': 'سياسة الاسترجاع',
          'terms_of_service': 'شروط الخدمة',
          'privacy_policy': 'سياسة الخصوصية',
          'delete_account': 'حذف الحساب',
          'delete_account_message': 'هل أنت متأكد من أنك تريد حذف حسابك؟',
          'account_deleted': 'تم حذف الحساب',
          'loading': 'جاري التحميل',
          'leauges_ranking': 'ترتيب البطولات',
          'players_ranking': 'ترتيب الهدافين',
          'retry': 'إعادة المحاولة',
          'not_available': 'غير متوفر',
          'connect_error': 'خطأ في الإتصال',
          'connection_error': 'خطأ في الإتصال',
          'connect_error_message': 'تأكد من إتصالك بالإنترنت',
          'server_error': 'خطأ في الخادم',
          'server_error_message': 'حدث خطأ ما، حاول مرة أخرى لاحقاً',
          'no_data': 'لا يوجد بيانات',
          'no_data_message': 'لا يوجد بيانات',
          'apply': 'تطبيق',
          'add_to_cart': 'أضف إلى السلة',
          'email': 'البريد الإلكتروني',
          'send': 'إرسال',
          'logout': 'تسجيل الخروج',
          'exit_confirm_msg': 'هل أنت متأكد من أنك تريد الخروج؟',
          'vat': 'ضريبة القيمة المضافة',
          'yes': 'نعم',
          'no': 'لا',
          'now': 'الآن',
          'year': 'سنة',
          'month': 'شهر',
          'day': 'يوم',
          'hour': 'ساعة',
          'minute': 'دقيقة',
          "second": "ثانية",
          "cancel": "إلغاء",
          "success": "نجاح",
          'our_policy': 'سياستنا',
          "policy_desc":
              "نحن نقدم مجموعة واسعة من بطاقات الهدايا التي تناسب جميع الأذواق والمناسبات. نوفر أيضًا إمكانية إنشاء بطاقة هدايا مخصصة بتصميمك مع إضافة نصك الخاص.",
          'search': 'بحث',
          'ready_card_for_you': 'بطاقات جاهزة لك',
          'done': 'تم',
          // currency
          'balance': 'الرصيد',
          'sar': 'رس',
          'sar.': 'ر.س',
          //Login and signup
          'login': 'تسجيل الدخول',
          'signup': 'إنشاء حساب',
          'login_to_continue': 'تسجيل الدخول للمتابعة',
          'forget_password': 'هل نسيت كلمة المرور؟',
          'restore_password': 'استعادة كلمة المرور',
          'password_reset': 'إعادة تعيين كلمة المرور',
          'password_reset_success': 'تم إعادة تعيين كلمة المرور بنجاح',
          'password_required': 'كلمة المرور مطلوبة',
          'not_login_msg': 'أنت لم تقم بتسجيل الدخول',
          'don\'t_have_account': 'ليس لديك حساب؟',
          'create_account': 'أنشئ حساب جديد',
          'password': 'كلمة المرور',
          'first_name': 'الاسم الأول',
          'last_name': 'الاسم الأخير',
          'fill_all_fields': 'يرجى ملء جميع الحقول',
          // reset password
          'email_sent':
              'تم إرسال رمز إعادة تعيين كلمة المرور إلى البريد الإلكتروني',
          'email_not_sent': 'لم يتم إرسال البريد الإلكتروني',
          // Profile
          "profile": "الملف الشخصي",
          "my_account": "حسابي",
          "wallet": "المحفظة",
          'my_wallet': 'محفظتي',
          'previous_transactions': 'العمليات السابقة',
          'transfer_no': 'تحويل رقم',
          'operations': 'العمليات',
          "current_balance": "الرصيد الحالي",
          'add_balance': 'إضافة رصيد',
          'balance_added': 'تمت إضافة الرصيد',
          'balance_add_failed': 'فشل إضافة الرصيد',
          'transfer_balance': 'تحويل الرصيد',
          'transfer': 'تحويل',
          'balance_transfered': 'تم تحويل الرصيد',
          'balance_transfer_failed': 'فشل تحويل الرصيد',
          'my_cards': 'بطاقاتي',
          'my_info': 'معلوماتي',
          'account_settings': 'إعدادات الحساب',
          'support': 'خدمة العملاء',
          'contact_us': 'تواصل معنا',
          'orders': 'الطلبات',
          'order_data': 'بيانات الطلب',
          'customer_and_recipient': 'العميل والمستلم',
          'id_and_date': 'الرقم والتاريخ',
          'update_profile': 'تحديث الحساب',
          'update': 'تحديث',
          'change_password': 'تغيير كلمة المرور',
          'old_password': 'كلمة المرور القديمة',
          'password_updated': 'تم تغيير كلمة المرور بنجاح',
          'update_failed': 'فشل التحديث',
          'profile_updated': 'تم تحديث الحساب',
          'new_password': 'كلمة المرور الجديدة',
          'confirm_password': 'تأكيد كلمة المرور',
          'unmatch_password': 'كلمة المرور غير متطابقة',
          'empty_old_pass': 'الرجاء إدخال كلمة المرور القديمة',
          'empty_new_pass': 'الرجاء إدخال كلمة المرور الجديدة',
          'empty_confirm_pass': 'الرجاء تأكيد كلمة المرور',
          'password_not_match': 'كلمات المرور غير متطابقة',
          // Reminder
          'phone_verify_reminder': 'يرجى أخذ لحظة للتحقق من رقم هاتفك.',
          "verify_phone_description":
              'ستتلقى رمز التحقق عبر الواتساب. الرجاء إدخال الرمز أدناه للمتابعة',
          'verify_email_description':
              'ستتلقى رمز التحقق عبر البريد الإلكتروني. الرجاء إدخال الرمز أدناه للمتابعة',
          // Transfer Balance
          'receiver_email': 'بريد المستلم',
          'receiver_phone_number': 'رقم الجوال للمستلم',
          'transfer_success': 'تم التحويل بنجاح',
          'transfer_failed': 'فشل التحويل',
          // Orders
          "no_orders": "لا يوجد طلبات",
          'order_number': 'رقم الطلب',
          'tax_number': 'الرقم الضريبي',
          'card_id': 'رقم البطاقة',
          // Cart
          'cart': 'السلة',
          'view_cart': 'عرض السلة',
          "empty_cart": "لا يوجد عناصر في السلة",
          "delivered": "تم التوصيل",
          "not_delivered": "لم يتم التوصيل",
          'delete': 'حذف',
          'add_to_cart_success': 'تمت إضافة البطاقة بنجاح',
          'add_to_cart_failed': 'فشلت إضافة البطاقة',
          'remove_card': 'حذف البطاقة',
          'remove_card_message': 'هل أنت متأكد من أنك تريد حذف هذه البطاقة؟',
          'removing_card': 'جاري حذف البطاقة',
          // Card Preview
          'card_preview': 'معاينة البطاقة',
          'customer': 'العميل',
          'view_card': 'عرض البطاقة',
          'view_invoice': 'عرض الفاتورة',
          'date': 'التاريخ',
          'time': 'الوقت',
          'delivery_not_set': 'لم يتم تحديد التوصيل',
          'card_ready': 'البطاقة جاهزة للاستخدام',
          'card_used': 'البطاقة مستخدمة',
          'how_to_use': 'كيفية الاستخدام',
          'close': 'إغلاق',
          'description': "الوصف",
          "card_details": "تفاصيل البطاقة",
          "card_info": 'معلومات البطاقة',
          'available_until': "متاحة حتى",
          "card_valid": "صلاحية البطاقة",
          'follow_instructions': 'اتبع الخطوات الاتية',
          'instruction_1': 'اذهب إلى موقع المتجر من خلال الرابط',
          'instruction_2': 'انسخ رمز القسيمة',
          'instruction_3': 'الصق الرمز في حقل الإدخال المخصص',
          'instruction_4': 'احصل على خصمك من المتجر',
          // HOW to use card
          'step_1': 'اذهب إلى موقع المتجر من خلال الرابط',
          'here': 'هنا',
          'step_2': 'انسخ رمز العرض',
          'step_3': 'الصق الرمز في الحقل المخصص',
          'step_4': 'احصل على خصمك من المتجر',
          // Payment
          'select_payment_method': 'اختر طريقة الدفع',
          'payment_method': 'طريقة الدفع',
          'amount': 'المبلغ',
          'payment': 'الدفع',
          'pay': 'ادفع',
          "pay_now": "ادفع الآن",
          'charge': 'عبء',
          'select_Payment': 'إختر طريقة دفع',
          'payment_success': 'تم الدفع بنجاح',
          'payment_failed': 'فشل الدفع',
          'unselected_payment_msg': 'يرجى اختيار طريقة دفع',
          'enter_amount_msg': 'يرجى إدخال المبلغ',
          'total_price': 'السعر الكلي',
          'coupon_code': 'كود الخصم',
          'coupon_apply_succ': 'تم تطبيق الكوبون بنجاح',
          'summary': 'الملخص',
          'buy': 'إشتري',
          'buy_now': 'إشتري الآن',
          'payment_success_message': 'تم الدفع بنجاح',
          'payment_failed_message': 'فشل الدفع',
          'paying': 'جاري الدفع',
          // Home
          'home_body': 'هديتهم على ذوقهم',
          'home_desc': 'عندما تصبح الهدية شخصية',
          'custom_a_gift': 'تخصيص هدية',
          'store_features': 'مميزات المتجر',
          "choose_what_suits_you": "اختر ما يناسبك",
          "gift_cards": "بطاقات الهدايا",
          "gift_cards_desc": "اختر بطاقة هدية من مجموعتنا الواسعة",
          "custom_cards": "بطاقات مخصصة",
          "custom_card": "بطاقة الهدايا المخصصة",
          "custom_cards_desc": "أنشئ بطاقة هدية مخصصة لأحبائك",
          'feature_1': 'تسليم فوري',
          'feature_1_msg':
              'استمتع بتسليم البطاقة الرقمية في اللحظة نفسها فور الشراء.',
          'feature_2': 'تشكيلة متنوعة',
          'feature_2_msg': 'تشكيلة واسعة تناسب جميع المناسبات.',
          'feature_3': 'تجربة شراء آمنة',
          'feature_3_msg': 'معاملات سريعة وآمنة تضمن راحة بالك.',
          // Cards
          'card': 'بطاقة',
          'from_behind': 'من الخلف',
          'custom_a_card': 'تخصيص بطاقة',
          'pro_item': 'عنصر مميز',
          'ready_cards': 'البطائق الجاهزة',
          'ready_card': 'بطاقة جاهزة',
          'cards_title_msg': 'بطاقات جاهزة لك',
          'empty_message': 'الرسالة فارغة',
          'empty_price': 'السعر فارغ',
          'min_price': 'السعر الادنى',
          'card_price': 'سعر البطاقة',
          'creat_a_card': 'صمم بطاقتك',
          "send_at": "إرسال في",
          "receive_at": "استلام في",
          "choose_time": "اختر الوقت",
          'celebration_shape': 'شكل الاحتفال',
          "choose_celebration_shape": "اختر شكل الاحتفال",
          'celebration_link': 'رابط الاحتفال',
          'choose_celebration_link': 'اختر رابط الاحتفال',
          'pro_color_info':
              'لقد اخترت لونًا مميزًا. سيتم إضافة رسوم إضافية تلقائيًا إلى سعر البطاقة',
          'pro_shape_info':
              'لقد اخترت شكلًا مميزًا. سيتم إضافة رسوم إضافية تلقائيًا إلى سعر البطاقة',
          "celebration_shape_info":
              "لقد اخترت شكل احتفال مميز. سيتم إضافة رسوم إضافية تلقائيًا إلى سعر البطاقة",
          "celebration_link_info":
              "لقد اخترت رابط احتفال مميز. سيتم إضافة رسوم إضافية تلقائيًا إلى سعر البطاقة",
          "card_added_successfully": "تمت إضافة البطاقة بنجاح",
          'shape_price': 'سعر الشكل',
          'color_price': 'سعر اللون',
          'celebration_shape_price': 'سعر شكل الاحتفال',
          'celebration_link_price': 'سعر رابط الاحتفال',
          // Explore
          'explore': 'استكشف',
          'categories': 'التصنيفات',
          'category': 'تصنيف',
          'show_all': 'عرض الكل',
          'partners_offers': 'عروض الشركاء',
          'popular_shops': 'المتاجر الاكثر طلبا',
          'latest_cards': 'أحدث البطاقات',
          'offers': 'العروض',
          'no_ads_found': 'لم يتم العثور على عروض',
          // ready
          'cards': 'البطاقات',
          'filter': 'تصفية',
          'price': 'السعر',
          'shop': 'المتجر',
          'shops': 'المتاجر',
          "reciver_info": "بيانات المستلم",
          "name": "الاسم",
          // custom
          'color': 'اللون',
          'font_type': 'نوع الخط',
          'font_size': 'حجم الخط',
          'shape': 'التصميم',
          'message': 'الرسالة',
          'receiver_name': 'اسم المستلم',
          'receiver_whats': 'واتساب المستلم',
          'sending_date': 'تاريخ ووقت الارسال',
          'please_enter_name': 'الرجاء إدخال الاسم',
          'please_enter_phone': 'الرجاء إدخال الهاتف',
          'phone_sould_not_start_with_0': 'لا يبدأ بـ0',
          'phone_should_be_9_digits': 'يحتوي على 9 أرقام',
          'phone_number': 'رقم الهاتف',
          'later': 'لاحقا',
          'save': 'حفظ',
          'next': 'التالي',
          'previous': 'السابق',
          // Shops
          'shops_title_msg': 'قائمة المتاجر',
          'store_name': 'اسم المتجر',
          'store_description': 'وصف المتجر',
          'store_link': 'رابط المتجر',
          'store': 'متجر',
          'no_stores': 'لا يوجد متاجر',
          // webview
          'open_in_browser': 'فتح في المتصفح',
          'copy_link': 'نسخ الرابط',
          'copied': 'تم النسخ',
          'leave': 'مغادرة',
          // Settings
          'home': 'الرئيسية',
          'menu': 'القائمة',
          'settings': 'الإعدادات',
          'about_app': 'عن التطبيق',
          'about_app_message':
              'اكتشف عالم الهدايا الرقمية! أرسل بطاقات هدايا إلكترونية مخصصة للأصدقاء والعائلة ببضع نقرات فقط. اختر من بين أفضل العلامات التجارية والمتاجر، مثالية لأي مناسبة.',
          'ok': 'حسناً',
          // Settings
          'verify_phone_msg': 'يرجى أخذ لحظة والتحقق من رقم الجوال الخاص بك',
          'profile_settings': 'إعدادات الحساب',
          'verify': 'تحقق',
          'send_code': 'إرسال الكود',
          'sending_code': 'ارسال رمز التحقق',
          'empty_feild': 'الحقل فارغ',
          'pin_minimim': 'الحد الأدنى للرمز السري',
          'phone_verify_success': 'تم التحقق من رقم الهاتف بنجاح',
          'dark_mode': 'الوضع الليلي',
          'language': 'اللغة',
          'notifications': 'إشعارات',
          'privacy': 'سياسة الخصوصية',
          'feed_back': 'شكراً للمساعدة',
          'feed_back_message':
              'للمساعدة في تطوير التطبيق يمكنك التواصل معنا على البريد الإلكتروني التالي',
          'email_clipbord_message': 'تم نسخ البريد الإلكتروني',
          'version': 'الإصدار',
          'join_us_msg': 'انظم الى شركاء GIVE A GIFT',
          // Join Us
          'please_enter_store_name': 'الرجاء إدخال اسم المتجر',
          'store_name_must_be_at_least_3_characters':
              'اسم المتجر يجب أن يكون على الأقل 3 أحرف',
          'please_enter_message_description': 'الرجاء إدخال رسالة',
          'message_must_be_at_least_10_characters':
              'الرسالة يجب أن يكون على الأقل 10 أحرف',
          'please_enter_store_description': 'الرجاء إدخال وصف المتجر',
          'store_description_must_be_at_least_10_characters': 'وصف المتجر يجب أن يكون على الأقل 10 أحرف',
          'please_enter_store_link': 'الرجاء إدخال رابط المتجر',
          'please_enter_valid_link': 'الرجاء إدخال رابط صحيح',
          'phone_must_be_at_least_9_digits':
              'رقم الهاتف يجب أن يحتوي على 10 أرقام',
          'please_enter_email': 'الرجاء إدخال البريد الإلكتروني',
          'please_enter_valid_email': 'الرجاء إدخال بريد إلكتروني صحيح',
          // Contact Us
          'name_must_be_at_least_3_characters':
              'الاسم يجب أن يكون على الأقل 3 أحرف',
          'please_enter_description': 'الرجاء إدخال الوصف',
          'description_must_be_at_least_10_characters':
              'الوصف يجب أن يكون على الأقل 10 أحرف',
          // Months:
          'month_1': 'يناير',
          'month_2': 'فبراير',
          'month_3': 'مارس',
          'month_4': 'أبريل',
          'month_5': 'مايو',
          'month_6': 'يونيو',
          'month_7': 'يوليو',
          'month_8': 'أغسطس',
          'month_9': 'سبتمبر',
          'month_10': 'أكتوبر',
          'month_11': 'نوفمبر',
          'month_12': 'ديسمبر',
          // Support
          'support_1':
              'إذا كنت بحاجة إلى مساعدة، لا تتردد في التواصل مع فريق الدعم الخاص بنا',
          'support_2': 'مكنك زيارة صفحتنا على إنستغرام',
          'support_3': 'للمزيد من المعلومات. نحن سعداء لمساعدتك',
          // Timing
          'pm': 'مساءً',
          'am': 'صباحًا'
        },
      };
}
