import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'app_name': 'Sport Live',
      'vpn_detected': 'VPN Detected',
      'security_alert': 'Security Alert',
      'rooted_device_msg': 'Your device is rooted, please use a non-rooted device to continue using the app',
      'vpn_detected_message': 'Please turn off your VPN to continue using the app',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'loading': 'Loading',
      'contact_twitter': 'Contact us on Twitter',
      'error': 'Error',
      'retry': 'Retry',
      'not_available': 'Not Available',
      'connect_error': 'Connection Error',
      'connection_error': 'Connection Error',
      'connect_error_message': 'Please check your internet connection',
      'server_error': 'Server Error',
      'server_error_message': 'Something went wrong, please try again later',
      'no_data': 'No Data',
      'no_data_message': 'No data found',
      // webview
      'open_in_browser': 'Open in browser',
      'copy_link': 'Copy link',
      'copied': 'Copied',
      'leave': 'Leave',
      // chats
      'home': 'Home',
      // settings
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'privacy': 'Privacy',
      'feed_back': 'Feedback',
      'feed_back_message': 'To help improving our application you can email us',
      'email_clipbord_message': 'Email has been copied',
      'version': 'Version',
    },
    'ar': {
      'app_name': 'رياضة مباشرة',
      'security_alert': 'تحذير أمني',
      'rooted_device_msg': 'جهازك يحتوي صلاحية الروت، يرجى إستخدام جهاز غير مروت لمواصلة إستخدام التطبيق',
      'vpn_detected': 'تم الكشف عن VPN',
      'vpn_detected_message': 'يرجى إيقاف VPN لمواصلة استخدام التطبيق',
      'contact_twitter': 'تواصل معنا على تويتر',
      'terms_of_service': 'شروط الخدمة',
      'privacy_policy': 'سياسة الخصوصية',
      'loading': 'جاري التحميل',
      'leauges_ranking': 'ترتيب البطولات',
      'players_ranking': 'ترتيب الهدافين',
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'not_available': 'غير متوفر',
      'connect_error': 'خطأ في الإتصال',
      'connection_error': 'خطأ في الإتصال',
      'connect_error_message': 'تأكد من إتصالك بالإنترنت',
      'server_error': 'خطأ في الخادم',
      'server_error_message': 'حدث خطأ ما، حاول مرة أخرى لاحقاً',
      'no_data': 'لا يوجد بيانات',
      'no_data_message': 'لا يوجد بيانات',
      // webview
      'open_in_browser': 'فتح في المتصفح',
      'copy_link': 'نسخ الرابط',
      'copied': 'تم النسخ',
      'leave': 'مغادرة',
      // chats
      'home': 'الصفحة الرئيسية',
      'menu': 'القائمة',
      'settings': 'الإعدادات',
      'about_app': 'عن التطبيق',
      'about_app_message': 'تطبيق كرة القدم يقدم مباريات كرة القدم المباشرة والأخبار والإحصائيات',
      'ok': 'حسناً',
      // settings
      'dark_mode': 'الوضع الليلي',
      'language': 'اللغة',
      'privacy': 'سياسة الخصوصية',
      'feed_back': 'شكراً للمساعدة',
      'feed_back_message': 'للمساعدة في تطوير التطبيق يمكنك التواصل معنا على البريد الإلكتروني التالي',
      'email_clipbord_message': 'تم نسخ البريد الإلكتروني',
      'version': 'الإصدار',
    },
  };

}
