import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'app_name': 'Sport Live',
      'vpn_detected': 'VPN Detected',
      'security_alert': 'Security Alert',
      'rooted_device_msg': 'Your device is rooted, please use a non-rooted device to continue using the app',
      'vpn_detected_message': 'Please turn off your VPN to continue using the app',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'contact_twitter': 'Contact us on Twitter',
      'cancel_sub': 'Cancel Subscription',
      'channels': 'Channels',
      'leagues': 'Leauges',
      'league': 'League',
      'venue': 'Venue',
      'city': 'City',
      'country': 'Country',
      'match_time': 'Match Time',
      'match_date': 'Match Date',
      'cancel': 'Cancel',
      'loading': 'Loading',
      'favorite': 'Favorite',
      'leauges_ranking': 'Leauges Table',
      'players_ranking': 'Top Scorers',
      'error': 'Error',
      'retry': 'Retry',
      'not_available': 'Not Available',
      'connect_error': 'Connection Error',
      'connection_error': 'Connection Error',
      'connect_error_message': 'Please check your internet connection',
      'server_error': 'Server Error',
      'server_error_message': 'Something went wrong, please try again later',
      'no_data': 'No Data',
      'no_data_message': 'No data found',
      'no_favorite': 'No Favorite',
      'no_favorite_message': 'No favorite found',
      'added_to_favorite': 'Added to favorite',
      'removed_from_favorite': 'Removed from favorite',
      // Search
      'lbl_team_search': 'Search for team',
      // details
      'details': 'Details',
      'match_details': 'Match Details',
      'match_status': 'Match Status',
      'statistics': 'Statistics',
      'lineups': 'Lineups',
      'First Half': 'First Half',
      'Second Half': 'Second Half',
      'First Half Extra Time': 'First Half Extra Time',
      'Second Half Extra Time': 'Second Half Extra Time',
      'Penalties': 'Penalties',
      'Match Finished': 'Match Finished',
      'Not Started': 'Not Started',
      'Time to be defined': 'Time to be defined',
      'Match Postponed': 'Match Postponed',
      'Match Cancelled': 'Match Cancelled',
      'Halftime': 'Halftime',
      // statistics
      'possession': 'Possession',
      // events
      'events': 'Events',
      'Goal': 'Goal',
      'Normal Goal': 'Normal Goal',
      'Own Goal': 'Own Goal',
      'Yellow Card': 'Yellow Card',
      'Red Card': 'Red Card',
      'Substitution': 'Substitution',
      'Penalty': 'Penalty',
      'Missed Penalty': 'Missed Penalty',
      'Kick Off': 'Kick Off',
      'Shots on Goal': 'Shots on Goal',
      'Shots off Goal': 'Shots off Goal',
      'Total Shots': 'Total Shots',
      'Blocked Shots': 'Blocked Shots',
      'Shots insidebox': 'Shots insidebox',
      'Shots outsidebox': 'Shots outsidebox',
      'Fouls': 'Fouls',
      'Corner Kicks': 'Corner Kicks',
      'Offsides': 'Offsides',
      'Ball Possession': 'Ball Possession',
      'Yellow Cards': 'Yellow Cards',
      'Red Cards': 'Red Cards',
      'Goalkeeper Saves': 'Goalkeeper Saves',
      'Total passes': 'Total passes',
      'Passes accurate': 'Passes accurate',
      'Passes %': 'Passes %',
      'expected_goals': 'Expected Goals',
      'Expected Goals': 'Expected Goals',
      'Match ended': 'Match ended',
      // webview
      'open_in_browser': 'Open in browser',
      'copy_link': 'Copy link',
      'copied': 'Copied',
      'leave': 'Leave',
      // chats
      'home': 'Home',
      'menu': 'Menu',
      'settings': 'Settings',
      'about_app': 'About Application',
      'about_app_message': 'A football application that provides live football matches, news and statistics',
      'ok': 'Ok',
      'search': 'Type to search',
      'profile': 'Profile',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      // chat
      'message_box_hint': 'Write message',
      'message_too_long': 'Message is too long',
      'message_copied': 'Message has been copied',
      'sent': 'Sent a',
      'image': 'Image',
      'file': 'File',
      'sent_now': 'Sent now',
      'go_to_chat': 'Go to chat',
      // payment
      'pay': 'Pay',
      'payment': 'Payment',
      'payment_method': 'Payment Method',
      'payment_method_error': 'Payment Method is required',
      'invoice_number': 'Invoice Number',
      'amount': 'Amount',
      'amount_error': 'Amount is required',
      'amount_too_low': 'Amount is too low',
      'request_payment': 'Pay to start Conversation',
      'blank_payments': 'You have no payments transaction',
      'payment_amount': 'Payment Amount',
      'payment_status': 'Payment Status',
      'payment_success': 'Payment Success',
      'payment_success_message': 'Payment has been successfully completed',
      'payment_created_success': 'Payment Created',
      'payment_failed': 'Payment Failed',
      'payment_failed_message': 'Payment has been failed',
      'payemnt_creating_failed': 'Payment Creating Failed',
      'payment_canceled': 'Payment Canceled',
      'payment_canceled_message': 'Payment has been canceled',
      'pending': 'Pending',
      'paid': 'Paid',
      'fee': 'Fee',
      'canceled': 'Canceled',
      'checkout': 'Checkout',
      'go_to_checkout': 'Go to checkout',
      // settings
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'privacy': 'Privacy',
      'feed_back': 'Feedback',
      'feed_back_message': 'To help improving our application you can email us',
      'email_clipbord_message': 'Email has been copied',
      'version': 'Version',
      // login - signup
      'email': 'Email',
      'email_error': 'Email is invalid',
      'password': 'Password',
      'password_error': 'Password is invalid',
      'sign_up_message': 'You don\'t have an account? Sign Up now',
      'user_name': 'Username',
      'full_name': 'Full Name',
      'sign_in_message': 'You already have an account? Sign In',
      'user_name_sign_up_error': 'Username is too short',
      'name': 'Name',
      'name_error': 'Name is too short',
      'last_name': 'Last Name',
      'last_name_error': 'Last Name is too short',
      'type_question': 'Do you want to sign up as an advisor?',
      'user': 'User',
      'advisor': 'Advisor',
      // profile
      'update_profile_image_success': 'Profile picture updated successfully',
      'update_profile_image_error': 'Profile picture update failed',
      'phone_number': 'Phone Number',
      'user_type': 'User Type',
      'not_set': 'Not Set',
      'username_updated': 'Username updated successfully',
      // days
      'sunday': 'Sunday',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      // months
      'year': 'Year',
      'month': 'Month',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'Mar',
      'apr': 'Apr',
      'may': 'May',
      'jun': 'Jun',
      'july': 'July',
      'aug': 'Aug',
      'sep': 'Sep',
      'oct': 'Oct',
      'nov': 'Nov',
      'dec': 'Dec',
      // timing
      'am': 'AM',
      'pm': 'PM',
      'live_match': 'Live',
      'live': 'Live',
      'coming': 'Coming',
      'ended': 'Ended',
      'postponed': 'Postponed',
      'cancelled': 'Cancelled',
      'time_to_be_defined': 'Time to be defined',
      'unknown': 'Unknown',
      // teams
      'team_name': 'Team',
      'team': 'Team',
      'played': 'Played',
      'win': 'Win',
      'draw': 'Draw',
      'lose': 'Lose',
      'goals_for': 'Goals For',
      'goals_against': 'Goals Against',
      'goals_difference': 'Goals Difference',
      'p': 'P',
      'w': 'W',
      'd': 'D',
      'l': 'L',
      'goals': 'Goals',
      'points': 'Points',
      "player": "Player",
      "penalties": "Penalties",
      // ADS
      'ads': 'ADS',
      'remove_ads': 'Remove Ads',
      'ads_message_1': 'Get All of the features of the app without any ads! and watch your favorite matches without any interruption',
      'ads_message_2': 'No More Ads for',
      //
      'and': 'and',
    },
    'ar': {
      'app_name': 'رياضة مباشرة',
      'security_alert': 'تحذير أمني',
      'rooted_device_msg': 'جهازك يحتوي صلاحية الروت، يرجى إستخدام جهاز غير مروت لمواصلة إستخدام التطبيق',
      'vpn_detected': 'تم الكشف عن VPN',
      'vpn_detected_message': 'يرجى إيقاف VPN لمواصلة استخدام التطبيق',
      'contact_twitter': 'تواصل معنا على تويتر',
      'terms_of_service': 'شروط الخدمة',
      'privacy_policy': 'سياسة الخصوصية',
      'cancel_sub': 'إلغاء الإشتراك',
      'channels': 'القنوات',
      'leagues': 'البطولات',
      'league': 'البطولة',
      'venue': 'الملعب المبارات',
      'city': 'المدينة',
      'country': 'Country',
      'match_time': 'وقت المباراة',
      'match_date': 'تاريخ المباراة',
      'cancel': 'إلغاء',
      'loading': 'جاري التحميل',
      'favorite': 'المفضلة',
      'leauges_ranking': 'ترتيب البطولات',
      'players_ranking': 'ترتيب الهدافين',
      'error': 'خطأ',
      'retry': 'إعادة المحاولة',
      'not_available': 'غير متوفر',
      'connect_error': 'خطأ في الإتصال',
      'connection_error': 'خطأ في الإتصال',
      'connect_error_message': 'تأكد من إتصالك بالإنترنت',
      'server_error': 'خطأ في الخادم',
      'server_error_message': 'حدث خطأ ما، حاول مرة أخرى لاحقاً',
      'no_data': 'لا يوجد بيانات',
      'no_data_message': 'لا يوجد بيانات',
      'added_to_favorite': 'تمت الإضافة للمفضلة',
      'removed_from_favorite': 'تمت الإزالة من المفضلة',
      // Search
      'lbl_team_search': 'إبحث عن فريق',
      // details
      'details': 'التفاصيل',
      'match_details': 'تفاصيل المباراة',
      'match_status': 'حالة المباراة',  
      'statistics': 'الإحصائيات',
      'lineups': 'التشكيلة',
      'First Half': 'الشوط الأول',
      'Second Half': 'الشوط الثاني',
      'First Half Extra Time': 'الشوط الأول إضافي',
      'Second Half Extra Time': 'الشوط الثاني إضافي',
      'Penalties': 'ضربات الجزاء',
      'Match Finished': 'إنتهت المباراة',
      'Not Started': 'لم تبدأ',
      'Time to be defined': 'الوقت غير محدد',
      'Match Postponed': 'تم تأجيل المباراة',
      'Match Cancelled': 'تم إلغاء المباراة',
      'Halftime': 'نهاية الشوط',
      // statistics
      'possession': 'الإستحواذ',
      // events
      'events': 'الأحداث',
      'Goal': 'هدف',
      'Normal Goal': 'هدف',
      'Own Goal': 'هدف بالخطأ',
      'Yellow Card': 'بطاقة صفراء',
      'Red Card': 'بطاقة حمراء',
      'Substitution': 'تبديل',
      'Penalty': 'ضربة جزاء',
      'Missed Penalty': 'ضربة جزاء ضائعة',
      'Kick Off': 'بداية المباراة',
      'Shots on Goal': 'التسديدات على المرمى',
      'Shots off Goal': 'التسديدات خارج المرمى',
      'Total Shots': 'إجمالي التسديدات',
      'Blocked Shots': 'التسديدات المحجوبة',
      'Shots insidebox': 'التسديدات داخل منطقة الجزاء',
      'Shots outsidebox': 'التسديدات خارج منطقة الجزاء',
      'Fouls': 'الخطايا',
      'Corner Kicks': 'ركنيات',
      'Offsides': 'تسلل',
      'Ball Possession': 'الإستحواذ على الكرة',
      'Yellow Cards': 'بطاقات صفراء',
      'Red Cards': 'بطاقات حمراء',
      'Goalkeeper Saves': 'إنقاذات الحارس',
      'Total passes': 'إجمالي التمريرات',
      'Passes accurate': 'التمريرات الصحيحة',
      'Passes %': 'نسبة التمريرات الصحيحة',
      'expected_goals': 'الأهداف المتوقعة',
      'Expected Goals': 'الأهداف المتوقعة',
      'Match ended': 'إنتهت المباراة',
      // webview
      'open_in_browser': 'فتح في المتصفح',
      'copy_link': 'نسخ الرابط',
      'copied': 'تم النسخ',
      'leave': 'مغادرة',
      // chats
      'home': 'الصفحة الرئيسية',
      'menu': 'القائمة',
      'settings': 'الإعدادات',
      'about_app': 'عن التطبيق',
      'about_app_message': 'تطبيق كرة القدم يقدم مباريات كرة القدم المباشرة والأخبار والإحصائيات',
      'ok': 'حسناً',
      'search': 'إضغط للبحث',
      'profile': 'الملف الشخصي',
      'sign_in': 'تسجيل الدخول',
      'sign_out': 'تسجيل الخروج',
      'sign_up': 'سجل',
      //chat
      'message_box_hint': 'أكتب رسالة',
      'message_too_long': 'الرسالة طويلة جداً',
      'message_copied': 'تم نسخ الرسالة',
      'sent': 'أرسل',
      'audio': 'رسالة صوتية',
      'image': 'صورة',
      'file': 'ملف',
      'sent_now': 'الآن',
      'go_to_chat': 'إذهاب للمحادثة',
      's': 'ث',
      'm': 'د',
      'h': 'س',
      //'d': 'ي',
      //'w': 'أ',
      // payment
      'pay': 'إدفع',
      'payment': 'الدفع',
      'payment_method': 'طريقة الدفع',
      'payment_method_error': 'طريقة الدفع مطلوبة',
      'invoice_number': 'رقم الفاتورة',
      'amount': 'المبلغ',
      'amount_error': 'المبلغ مطلوب',
      'amount_too_low': 'المبلغ قليل جداً',
      'request_payment': 'إدفع لبدأ المحادثة',
      'blank_payments': 'ليس لديك دفعات',
      'payment_amount': 'مبلغ الدفع',
      'payment_status': 'حالة الدفع',
      'payment_success': 'تم الدفع',
      'payment_success_message': 'تم الدفع بنجاح',
      'payment_created_success': 'تم إنشاء الدفع',
      'payment_failed': 'فشل الدفع',
      'payment_failed_message': 'فشل الدفع',
      'payemnt_creating_failed': 'فشل إنشاء الدفع',
      'payment_canceled': 'تم إلغاء الدفع',
      'payment_canceled_message': 'تم إلغاء الدفع',
      'pending': 'قيد الإنتظار',
      'paid': 'تم الدفع',
      'fee': 'الرسوم',
      'canceled': 'ملغي',
      'checkout': 'الدفع',
      'go_to_checkout': 'إذهاب للدفع',
      // settings
      'dark_mode': 'الوضع الليلي',
      'language': 'اللغة',
      'privacy': 'سياسة الخصوصية',
      'feed_back': 'شكراً للمساعدة',
      'feed_back_message': 'للمساعدة في تطوير التطبيق يمكنك التواصل معنا على البريد الإلكتروني التالي',
      'email_clipbord_message': 'تم نسخ البريد الإلكتروني',
      'version': 'الإصدار',
      // login - sign up
      'email': 'البريد الإلكتروني',
      'email_error': 'البريد الإلكتروني غير صحيح',
      'password': 'كلمه السر',
      'password_error': 'كلمة السر غير صحيحة',
      'sign_in_message': 'لديك حساب؟ تسجيل الدخول',
      'sign_up_message': 'ليس لديك حساب؟ سجل الآن',
      'user_name': 'إسم المستخدم',
      'full_name': 'الإسم الكامل',
      'user_name_sign_up_error': 'إسم المستخدم قصير جدا',
      'name': 'الإسم',
      'name_error': 'الاسم قصير جدا',
      'last_name': 'اللقب',
      'last_name_error': 'اللقب قصير جدا',
      'type_question': 'هل تريد التسجيل كمستشار؟',
      'user': 'مستخدم',
      'advisor': 'مستشار',
      // profile
      'update_profile_image_success': 'تم تحديث صورة الملف الشخصي بنجاح',
      'update_profile_image_error': 'فشل تحديث صورة الملف الشخصي',
      'phone_number': 'رقم الهاتف',
      'user_type':  'طبيعة المستخدم',
      'not_set': 'غير محدد',
      'username_updated': 'تم تحديث إسم المستخدم بنجاح',
      // days
      'sunday': 'الأحد',
      'monday': 'الإثنين',
      'tuesday': 'الثلاثاء',
      'wednesday': 'الأربعاء',
      'thursday': 'الخميس',
      'friday': 'الجمعة',
      'saturday': 'السبت',
      // months
      'year': 'سنة',
      'month': 'شهر',
      'jan': 'يناير',
      'feb': 'فبراير',
      'mar': 'مارس',
      'apr': 'أبريل',
      'may': 'مايو',
      'jun': 'يونيو',
      'july': 'يوليو',
      'aug': 'أغسطس',
      'sep': 'سبتمبر',
      'oct': 'أكتوبر',
      'nov': 'نوفمبر',
      'dec': 'ديسمبر',
      // timing
      'am': 'ص',
      'pm': 'م',
      'AM': 'صباحاً',
      'PM': 'مساءً',
      'live_match': 'جارية الآن',
      'live': 'مباشر',
      'coming': 'قادم',
      'ended': 'إنتهى',
      'postponed': 'مؤجل',
      'cancelled': 'ملغي',
      'time_to_be_defined': 'الوقت غير محدد',
      'unknown': 'غير معروف',
      // teams
      'team_name': 'الفريق',
      'team': 'فريق',
      'played': 'لعب',
      'win': 'فوز',
      'draw': 'تعادل',
      'lose': 'خسر',
      'goals_for': 'أهداف لصالح',
      'goals_against': 'أهداف ضد',
      'goals_difference': 'فارق الأهداف',
      'p': 'ل',
      'w': 'ف',
      'd': 'ت',
      'l': 'خ',
      'goals': 'أهداف',
      'points': 'النقاط',
      "player": "اللاعب",
      "penalties": "ضربات الجزاء",
      // ADS
      'ads': 'إعلانات',
      'remove_ads': 'إزالة الإعلانات',
      'ads_message_1': 'إحصل على كل مميزات التطبيق بدون أي إعلانات! وشاهد مبارياتك المفضلة بدون أي إنقطاع',
      'ads_message_2': 'لا إعلانات لمدة',
      //
      'and': 'و',
    },
  };

}
